### ISSUE TITLE
Counter for number of characters in the "Summarize your project" section when sharing/editing a project

### ISSUE THREAD

**Issue by ImpactMaker-2** [climateconnect/climateconnect#382] opened 2020-11-11 15:16 UTC
The summary of a climate project on Climate Connect only allows up to 240 characters (1 tweet) `frontend/src/components/shareProject/AddSummarySection.js` should show a counter of how many characters your summary has so far. 
This will help users to see how many characters they have left while writing their project's summary

**Comment by positiveimpact** [comment] 2021-01-14 07:26
@KParrish193 Are you still actively working on this issue?

**Comment by KParrish193** [comment] 2021-01-14 22:15
I am but am cool moving to something else if someone else needs to work on this, or it's not needed anymore.

**Comment by positiveimpact** [comment] 2021-01-15 06:14
> I am but am cool moving to something else if someone else needs to work on this, or it's not needed anymore.

Not, it's still needed and I'm fine with you working on it, just wanted to make sure the issue is still actively being worked on.

**Comment by positiveimpact** [comment] 2022-07-04 08:21
Fixed by #910

**Closed by positiveimpact** 2022-07-04 08:21 UTC
Labels: good first issue, Priority C
